Traceback (most recent call last):
  File "D:\projects\ctrguiautotests\Firefox\Working\test_GUI-13_Help_Button_Firefox.py", line 6, in <module>
    import guiLib
ImportError: No module named guiLib
Traceback (most recent call last):
  File "D:\projects\ctrguiautotests\Firefox\Working\test_GUI-13_Help_Button_Firefox.py", line 6, in <module>
    import guiLib
ImportError: No module named guiLib
Traceback (most recent call last):
  File "D:\projects\ctrguiautotests\Firefox\Working\test_GUI-13_Help_Button_Firefox.py", line 6, in <module>
    import guiLib
ImportError: No module named guiLib
Getting address: http://10.16.15.112
Window Resized
Login unsuccessful
Traceback (most recent call last):
  File "D:\projects\ctrguiautotests\Firefox\Working\\test_GUI-13_Help_Button_Firefox.py", line 21, in <module>
    handle = driver.window_handles
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 476, in window_handles
    return self.execute(Command.GET_WINDOW_HANDLES)['value']
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 162, in execute
    response = self.command_executor.execute(driver_command, params)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 349, in execute
    return self._request(command_info[0], url, body=data)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 379, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "c:\python27\lib\httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "c:\python27\lib\httplib.py", line 1001, in _send_request
    self.putrequest(method, url, **skips)
  File "c:\python27\lib\httplib.py", line 871, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest
